### ISSUE TITLE
Does not sort correctly

### ISSUE THREAD

**Issue by dkasaj** [chrisdl/nova-sort#8]
When sorting 2 items, "GO" and "Gallery", the result would be

GO
Gallery

Which is obviously not alphabetically sorted

**Comment by chrisdl** [comment]
Thanks for the report!

This is because uppercase characters are given preference. We use the regular [old javascript sort function](https://github.com/chrisdl/nova-sort/blob/5594b16829969824ee7a6322ca321c0bc7157db5/Sort.novaextension/Scripts/main.js#L23) So sorting

`abcABC` would result in `ABCabc`.

If you for example had the lines

```
Go
Gallery
```

It would correctly result in

```
Gallery
Go
```

I agree that this is a bit counterintuitive. What would you recommend @dkasaj? The way I see it we have 3 options:

1. Keep it the way it is
2. Make all sorting case insensitive
3. Add an optional setting where you can toggle whether you want case sensitive sorting or not.

Right now i'm leaning towards (3) the optional setting.

**Comment by dkasaj** [comment]
Thank you for considering the changes. 
#3 is okay but hopefully you'll make the default action to be case insensitive. 
By default people just want to end up with an alphabetically sorted list, and not worry if any items contains a capital second character (by mistake or not)

**Comment by craiga** [comment]
I'd like to humbly suggest a fourth option:

4. Add a "Sort Lines (Case Insensitive)" option to the menu.

That way I could quickly choose the behaviour I want while I'm in the menus/command palette.

For bonus points, you could combine this with option 3 and have the menu items change names. When the setting is enabled to prefer case-insensitive sorting, the existing "Sort Lines" menu item would become "Sort Lines (Case Sensitive)", and have the "Sort Lines (Case Insensitive)" menu item would become "Sort Lines".

**Comment by chrisdl** [comment]
Good suggestion @craiga !
